# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('debtor', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('taken_on', models.DateField()),
                ('date_due', models.DateField(blank=True, null=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
