# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('date_paid', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.Debt')),
            ],
        ),
    ]
