# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_debtpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
