# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_debt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='balance',
            field=models.FloatField(default=222.0),
            preserve_default=False,
        ),
    ]
