# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_debt_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DebtPayments',
            new_name='DebtPayment',
        ),
    ]
