# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(blank=True, default='', max_length=200)),
                ('account_no', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('date_created', models.DateField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SaccoTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.SaccoAccount')),
            ],
        ),
    ]
