# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankaccount_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.BankAccount')),
            ],
        ),
    ]
