# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.ExpenseCategory')),
            ],
        ),
    ]
