# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_incometransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incometransaction',
            old_name='expense_name',
            new_name='income_name',
        ),
    ]
